### ISSUE TITLE
🚀 Configure IaC scan Workflow to Trigger on Infra Directory Changes

### ISSUE THREAD

**Issue by 0GiS0** [0GiS0/tour-of-heroes-dotnet-api#83]
**Description:**
We need to configure our GitHub Actions workflow to trigger only when changes are made to the infrastructure directory (`infra/`). This ensures that our IaC (Infrastructure as Code) workflows are executed only when relevant files are modified.

**Proposed Solution:**
1. **Modify the GitHub Actions workflow configuration:**
   - Locate the workflow file (e.g., `.github/workflows/iac.yml`).

2. **Update the `on` trigger to include the `paths` filter:**
   - Use the following snippet to update the workflow file:

```yaml
name: Infrastructure as Code (IaC)

on:
  push:
    paths:
      - 'infra/**'
  pull_request:
    paths:
      - 'infra/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
```

3. **Test the workflow:**
   - Commit and push the changes to a new branch.
   - Open a pull request and ensure the workflow runs only when changes are made to the `infra/` directory.

**Additional Information:**
Please refer to the [GitHub Actions documentation](https://docs.github.com/en/actions) for more details on configuring workflows.
